version: '3.8'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
      - ./whls:/whls
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://sahar:1234@db/assist
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sahar 
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=assist

volumes:
  postgres_data:
