version: '3.8'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    volumes:
      - .:/app
      - ./whls:/whls
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://test:1234@db/assist
      - GIT_PYTHON_REFRESH=quiet
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test 
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=assist

  mlflow:

    image: ghcr.io/mlflow/mlflow
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000 
    command: sh -c "mlflow server --backend-store-uri postgresql://test:1234@db/assist --host=0.0.0.0 --serve-artifacts"
    volumes:
      - ./mlflow/data:/mlflow

volumes:
  postgres_data:
